# Generated by Django 5.0.6 on 2024-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lead_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_months', '2 Month'), ('three_months', '3 Month'), ('four_months', '4 Month'), ('five_months', '5 Month'), ('six_months', '6 Month'), ('more_than_six_months', '+6 Month')], default='two_weeks', max_length=50, null=True),
        ),
    ]
