# Generated by Django 5.0.6 on 2024-08-06 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lead_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='pushed_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pushed_time',
        ),
        migrations.AddField(
            model_name='lead',
            name='pushed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_months', '2 Months'), ('three_months', '3 Months'), ('four_months', '4 Months'), ('five_months', '5 Months'), ('six_months', '6 Months'), ('more_than_six_months', '+6 Months')], default='two_weeks', max_length=50, null=True),
        ),
    ]
