# Generated by Django 5.0.6 on 2024-08-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lead_pushed_date_remove_lead_pushed_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_status',
            new_name='status',
        ),
    ]
