# Generated by Django 5.0.6 on 2024-08-06 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_lead_status_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pushed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
