# Generated by Django 5.0.6 on 2024-08-07 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lead_pushed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('vacant_land', 'Vacant Land'), ('business', 'Business'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('mobile_home', 'Mobile Home')], default='house', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('callback', 'Callback'), ('duplicate', 'Duplicate')], default='pending', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadHandlingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handling_profile', to='core.profile')),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handling_user', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handling_camp', to='core.campaign')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handling_lead', to='core.lead')),
                ('lead_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_handling_db', to='core.leadhandlingsettings')),
            ],
        ),
    ]
