# Generated by Django 5.0.6 on 2024-08-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_leadhandlingdb_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
