# Generated by Django 5.0.6 on 2024-08-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lead_lead_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_flow_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('callback', 'Callback'), ('duplicated', 'Duplicated')], default='pending', max_length=50, null=True),
        ),
    ]
