# Generated by Django 5.0.6 on 2024-08-08 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lead_lead_flow_json_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(blank=True, choices=[('callers', 'Cold Callers'), ('sales', 'Sales'), ('dispo', 'Dispositions'), ('acq', 'Acquisitions'), ('data', 'Data Management'), ('quality', 'Quality'), ('team_leaders', 'Team Leaders')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('upl', 'UPL'), ('annual', 'Annual'), ('casual', 'Casual'), ('sick', 'Sick')], default='UPL', max_length=20, null=True)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_profile', to=settings.AUTH_USER_MODEL)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_profile', to='core.profile')),
                ('handled_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_by_leave', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_leave', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leave', to='core.team')),
            ],
        ),
    ]
