# Generated by Django 5.0.6 on 2024-08-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_team_team_type_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='agent',
            new_name='agen_user',
        ),
    ]
