# Generated by Django 5.0.6 on 2024-08-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_agent_leave_agen_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='agen_user',
            new_name='agent_user',
        ),
    ]
