# Generated by Django 5.0.6 on 2024-08-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_agen_user_leave_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='leave_files/'),
        ),
    ]
