# Generated by Django 5.0.6 on 2024-08-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_leave_handled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leader',
        ),
    ]
