# Generated by Django 5.0.6 on 2024-08-08 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_leave_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
