# Generated by Django 5.0.6 on 2024-08-09 15:49

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_leave_submission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.random_name_leave_files),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('accuser_name', models.CharField(blank=True, max_length=50, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('warning', 'Written Warning'), ('deduction', 'Deduction'), ('termination', 'Termination')], max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('deduction_amount', models.FloatField(blank=True, default=0, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.random_name_action_files)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('accuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_accuser', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_by_deduction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
