# Generated by Django 5.0.6 on 2024-08-09 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_leave_file_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='accuser_name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='agent_name',
        ),
        migrations.AlterField(
            model_name='action',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
