# Generated by Django 5.0.6 on 2024-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_profile_client_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='monthly_leadpoints_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
