# Generated by Django 5.0.6 on 2024-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_serversetting_monthly_leadpoints_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversetting',
            name='monthly_leadpoints_target',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
