# Generated by Django 5.0.6 on 2024-08-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_serversetting_monthly_leadpoints_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='negative_percentage',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='neutral_percentage',
            field=models.PositiveIntegerField(blank=True, default=80, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndisposetting',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_dispo', to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='leadhandlingsettings',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
    ]
