# Generated by Django 5.0.6 on 2024-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_serversetting_negative_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
