# Generated by Django 5.0.6 on 2024-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_lead_latitude_alter_lead_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
