# Generated by Django 5.0.6 on 2024-08-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_lead_county_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profile', to='core.profile'),
        ),
    ]
