# Generated by Django 5.0.6 on 2024-08-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_lead_updated_lead_aht_lead_assigned_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='aht',
            new_name='handling_time',
        ),
    ]
