# Generated by Django 5.0.6 on 2024-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_aht_lead_handling_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='handling_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
