# Generated by Django 5.0.6 on 2024-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_lead_handling_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fireback',
            field=models.BooleanField(default=False),
        ),
    ]
