# Generated by Django 5.0.6 on 2024-08-18 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_lead_fireback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('single', 'Single'), ('Multiple', 'Multiple')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile_feedback', to='core.profile')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_feedback', to=settings.AUTH_USER_MODEL)),
                ('auditor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_feedback', to='core.profile')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
            ],
        ),
    ]
