# Generated by Django 5.0.6 on 2024-08-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
