# Generated by Django 5.0.6 on 2024-08-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_feedback_phone_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
