# Generated by Django 5.0.6 on 2024-08-18 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_feedback_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
