# Generated by Django 5.0.6 on 2024-08-18 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_feedback_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leave',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
