# Generated by Django 5.0.6 on 2024-08-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_action_created_leave_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='campaign',
        ),
        migrations.AddField(
            model_name='feedback',
            name='campaign',
            field=models.ManyToManyField(blank=True, null=True, to='core.campaign'),
        ),
    ]
