# Generated by Django 5.0.6 on 2024-08-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_feedback_campaign_feedback_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='campaign',
            field=models.ManyToManyField(blank=True, to='core.campaign'),
        ),
    ]
