# Generated by Django 5.0.6 on 2024-08-19 01:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_feedback_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ready_time', models.DurationField(default=datetime.timedelta(0))),
                ('meeting_time', models.DurationField(default=datetime.timedelta(0))),
                ('break_time', models.DurationField(default=datetime.timedelta(0))),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('current_status', models.CharField(choices=[('ready', 'Ready'), ('meeting', 'Meeting'), ('break', 'Break')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
