# Generated by Django 5.0.6 on 2024-08-19 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_feedback_type_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='offline_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='current_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('meeting', 'Meeting'), ('break', 'Break'), ('offline', 'Offline')], max_length=20),
        ),
    ]
