# Generated by Django 5.0.6 on 2024-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_workstatus_date_workstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='break_paid',
            field=models.BooleanField(default=False),
        ),
    ]
