# Generated by Django 5.0.6 on 2024-08-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_serversetting_break_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialercredentials',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_dialercreds', to='core.profile'),
        ),
    ]
