# Generated by Django 5.0.6 on 2024-08-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_dialercredentials_agent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
