# Generated by Django 5.0.6 on 2024-08-26 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_workstatus_login_time_workstatus_logout_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('absence_date', models.DateField(blank=True, null=True)),
                ('absence_type', models.CharField(blank=True, choices=[('upl', 'UPL'), ('annual', 'Annual'), ('casual', 'Casual'), ('sick', 'Sick'), ('nsnc', 'No Show No Call')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile_absence', to='core.profile')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_user_absence', to=settings.AUTH_USER_MODEL)),
                ('reporter_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_profile_absence', to='core.profile')),
            ],
        ),
    ]
