# Generated by Django 5.0.6 on 2024-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
