# Generated by Django 5.0.6 on 2024-08-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_absence_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('casual', 'Casual'), ('sick', 'Sick'), ('upl', 'UPL'), ('nsnc', 'No Show No Call')], max_length=50, null=True),
        ),
    ]
