# Generated by Django 5.0.6 on 2024-09-03 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_seatassignmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignmentlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
