# Generated by Django 5.0.6 on 2024-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_seatassignmentlog_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='weekly_leads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
