# Generated by Django 5.1.1 on 2024-09-13 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_campaign_weekly_leads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='maps_theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark')], default='dark', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_flow_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maps_theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark')], default='dark', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings_theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark')], default='dark', max_length=50),
        ),
        migrations.AddIndex(
            model_name='workstatus',
            index=models.Index(fields=['user', 'last_status_change'], name='core_workst_user_id_045aca_idx'),
        ),
    ]
