# Generated by Django 5.1.1 on 2024-09-17 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_prepayment_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='time',
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
