# Generated by Django 5.1.1 on 2024-09-25 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_manualhours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('pushed', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('callback', 'Callback'), ('duplicated', 'Duplicated')], default='pending', max_length=50, null=True)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('quality_to_agent_notes', models.TextField(blank=True, null=True)),
                ('handling_time', models.DurationField(blank=True, null=True)),
                ('lead_flow', models.FloatField(blank=True, default=0, null=True)),
                ('lead_flow_json', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_agent_profile', to='core.profile')),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_agent_user', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_campaign', to='core.campaign')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LeadHandlingDB',
        ),
    ]
