# Generated by Django 5.1.1 on 2024-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_saleslead_delete_leadhandlingdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslead',
            old_name='quality_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='handling_time',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='quality_to_agent_notes',
        ),
        migrations.AddField(
            model_name='saleslead',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.CharField(blank=True, choices=[('follow_up', 'Follow Up'), ('scheduled_meeting', 'Scheduled Meeting'), ('no_show', 'No Show'), ('send_contract', 'To-Send Contract'), ('follow_up_landing', 'Follow Up-Landing'), ('landed', 'Landed'), ('longterm_follow_up', 'Long Term Follow Up'), ('unresponsive', 'Unresponsive'), ('not_interested', 'Not Interested')], default='pending', max_length=50, null=True),
        ),
    ]
