# Generated by Django 5.1.1 on 2024-09-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_rename_quality_notes_saleslead_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslead',
            name='lead_flow',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='lead_flow_json',
        ),
    ]
