# Generated by Django 5.1.1 on 2024-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_role_action_handling_role_action_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='admin_home',
            field=models.BooleanField(default=False),
        ),
    ]
