# Generated by Django 5.1.1 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_role_admin_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='activity_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='applications_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='crm_domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='leads_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='logins_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='prepayments_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='requests_webhook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
