# Generated by Django 5.1.1 on 2024-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_serversetting_activity_webhook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='admin_affiliates',
            field=models.BooleanField(default=False),
        ),
    ]
