# Generated by Django 5.1.1 on 2024-10-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_affiliateprofile_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_affiliate_profile', to='core.affiliateprofile'),
        ),
    ]
