# Generated by Django 5.1.1 on 2024-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_affiliateinvoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='affiliate_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
