# Generated by Django 5.1.1 on 2024-10-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_role_affiliate_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='lead_submission',
            field=models.BooleanField(default=False),
        ),
    ]
