# Generated by Django 5.1.1 on 2024-10-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_role_lead_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
