# Generated by Django 5.1.1 on 2024-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=50, null=True),
        ),
    ]
