# Generated by Django 5.1.1 on 2024-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_feedback_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='dialer_reports',
            field=models.BooleanField(default=False),
        ),
    ]
