# Generated by Django 5.1.1 on 2024-10-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_dialerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dialer_type',
            field=models.CharField(blank=True, choices=[('batchdialer', 'BatchDialer'), ('calltools', 'CallTools')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dialier_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialerreport',
            name='dialer',
            field=models.CharField(blank=True, choices=[('batchdialer', 'BatchDialer'), ('calltools', 'CallTools')], max_length=50, null=True),
        ),
    ]
