# Generated by Django 5.1.1 on 2024-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_campaign_dialer_type_campaign_dialier_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='dialier_api_key',
            new_name='dialer_api_key',
        ),
    ]
