# Generated by Django 5.1.1 on 2024-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_rename_dialier_api_key_campaign_dialer_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='client_campaign_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='client_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='client_lookerstudio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dialer_type',
            field=models.CharField(blank=True, choices=[('batchdialer', 'BatchDialer'), ('east1_calltools', 'east-1.calltools.io'), ('east2_calltools', 'east-2.calltools.io'), ('west2_calltools', 'west-2.calltools.io'), ('west3_calltools', 'west-3.calltools.io'), ('west4_calltools', 'west-4.calltools.io'), ('app_calltools', 'app.calltools.io'), ('staging_calltools', 'staging.calltools.io')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dialerreport',
            name='dialer',
            field=models.CharField(blank=True, choices=[('batchdialer', 'BatchDialer'), ('east1_calltools', 'east-1.calltools.io'), ('east2_calltools', 'east-2.calltools.io'), ('west2_calltools', 'west-2.calltools.io'), ('west3_calltools', 'west-3.calltools.io'), ('west4_calltools', 'west-4.calltools.io'), ('app_calltools', 'app.calltools.io'), ('staging_calltools', 'staging.calltools.io')], max_length=50, null=True),
        ),
    ]
