# Generated by Django 5.1.1 on 2024-10-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_role_company_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='company_tasks',
        ),
        migrations.AddField(
            model_name='role',
            name='operations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.CharField(blank=True, choices=[('executive_dep', 'Executive Management'), ('data_dep', 'Data Management'), ('workforce_dep', 'Workforce'), ('quality_dep', 'Quality'), ('dev_dep', 'Development'), ('sales_dep', 'Sales'), ('hr_dep', 'Human Resources'), ('accounting_dep', 'Accounting'), ('archive', 'Archive')], max_length=50, null=True),
        ),
    ]
