# Generated by Django 5.1.1 on 2024-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_remove_role_company_tasks_role_operations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
