# Generated by Django 5.1.1 on 2024-10-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_task_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_department',
        ),
    ]
