# Generated by Django 5.1.1 on 2024-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_rename_assigned_task_assigned_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, null=True, upload_to='server_settings'),
        ),
    ]
