# Generated by Django 5.1.1 on 2024-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_serversetting_apple_touch_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='tasks_webhook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
