# Generated by Django 5.1.1 on 2024-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_serversetting_tasks_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='trainer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
