# Generated by Django 5.1.1 on 2024-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_feedback_trainer_text_alter_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversetting',
            name='hide_campaign_leadform',
        ),
        migrations.RemoveField(
            model_name='serversetting',
            name='hide_client_leadform',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('panel_1', 'Panel 1'), ('panel_2', 'Panel 2'), ('panel_3', 'Panel 3')], default='pending', max_length=50, null=True),
        ),
    ]
