# Generated by Django 5.1.1 on 2024-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_serversetting_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversetting',
            name='about_us',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='facebook',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='instagram',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='linkedin',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='privacy',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='serversetting',
            name='terms',
            field=models.URLField(blank=True, default='/', null=True),
        ),
    ]
