# Generated by Django 5.1.1 on 2024-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_serversetting_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_discovery',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('referral', 'Referral'), ('company_website', 'Company Website'), ('job_portal', 'Job Portal'), ('direct_messages', 'Direct Messages'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
