# Generated by Django 5.1.1 on 2024-11-12 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_application_app_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
