# Generated by Django 5.1.1 on 2024-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_application_app_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bi_lingual', 'Bilingual'), ('cold_caller', 'Cold Caller'), ('lead_manager', 'Lead Manager'), ('dispositions_manager', 'Dispositions Manager'), ('acquisitions_manager', 'Acquisitions Manager'), ('data_manager', 'Data Manager'), ('b2c_sales', 'B2C Sales'), ('b2b_sales', 'B2B Sales'), ('csr', 'Customer Service Rep'), ('quality', 'QA Specialist'), ('team_leader', 'Team Leader'), ('account_manager', 'Account Manager'), ('opm', 'Operations Manager')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='language_exp',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='app_skills', to='core.applicationskill'),
        ),
    ]
