# Generated by Django 5.1.1 on 2024-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_applicationskill_application_language_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='skills',
        ),
        migrations.DeleteModel(
            name='ApplicationSkill',
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
