# Generated by Django 5.1.1 on 2024-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_workstatus_lateness'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='lateness_status',
            field=models.CharField(blank=True, choices=[('late', 'Late'), ('early', 'Early'), ('on_time', 'On Time')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='lateness',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
