# Generated by Django 5.1.1 on 2024-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_application_recording_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='deductible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='known_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('realestate', 'Real Estate'), ('roofing', 'Roofing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_department',
            field=models.CharField(blank=True, choices=[('executive_dep', 'Executive Management'), ('ops_dep', 'Operations Management'), ('data_dep', 'Data Management'), ('workforce_dep', 'Workforce'), ('quality_dep', 'Quality'), ('dev_dep', 'Development'), ('sales_dep', 'Sales'), ('hr_dep', 'Human Resources'), ('accounting_dep', 'Accounting'), ('archive', 'Archive')], max_length=50, null=True),
        ),
    ]
