# Generated by Django 5.1.1 on 2024-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_saleslead_campaign_remove_saleslead_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='documentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
