# Generated by Django 5.1.1 on 2024-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_campaign_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='campaign_documentation',
            field=models.BooleanField(default=False),
        ),
    ]
