# Generated by Django 5.1.1 on 2024-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_role_campaign_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qa_sop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='campaign_sop',
            field=models.BooleanField(default=False),
        ),
    ]
