# Generated by Django 5.1.1 on 2024-12-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_contractpackage_contractservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractService',
            new_name='Package',
        ),
        migrations.DeleteModel(
            name='ContractPackage',
        ),
    ]
