# Generated by Django 5.1.1 on 2024-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_contractsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsample',
            name='field',
            field=models.CharField(blank=True, choices=[('roofing', 'Roofing'), ('realestate', 'Real Estate')], max_length=100, null=True),
        ),
    ]
