# Generated by Django 5.1.1 on 2024-12-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_contractsample_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsample',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
