# Generated by Django 5.1.1 on 2024-12-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_contractsample_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='hours_acq',
            new_name='count_acq',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='hours_dm',
            new_name='count_dm',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='hours_lm',
            new_name='count_lm',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='hours_va',
            new_name='count_va',
        ),
    ]
