# Generated by Django 5.1.1 on 2024-12-05 02:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_rename_hours_acq_package_count_acq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_text', models.TextField(blank=True, null=True)),
                ('count_va', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_va', models.CharField(blank=True, max_length=100, null=True)),
                ('count_lm', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_lm', models.CharField(blank=True, max_length=100, null=True)),
                ('count_acq', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_acq', models.CharField(blank=True, max_length=100, null=True)),
                ('count_dm', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_dm', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.package')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractsample')),
            ],
        ),
    ]
