# Generated by Django 5.1.1 on 2024-12-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_rename_country_contractvisit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvisit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contract'),
        ),
    ]
