# Generated by Django 5.1.1 on 2024-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_contract_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
