# Generated by Django 5.1.1 on 2024-12-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_application_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='paid',
            new_name='forwarded',
        ),
        migrations.AddField(
            model_name='contract',
            name='strip_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
