# Generated by Django 5.1.1 on 2024-12-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_rename_paid_contract_forwarded_contract_strip_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='forwarded',
            new_name='clicked',
        ),
    ]
