# Generated by Django 5.1.1 on 2024-12-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_rename_forwarded_contract_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='deductible',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='insurance',
        ),
    ]
