# Generated by Django 5.1.1 on 2024-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_remove_lead_contractor_remove_lead_deductible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='qa_unassign_lead',
            field=models.BooleanField(default=False),
        ),
    ]
