# Generated by Django 5.1.1 on 2024-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_role_qa_unassign_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='field',
            field=models.CharField(blank=True, choices=[('roofing', 'Roofing'), ('realestate', 'Real Estate')], max_length=100, null=True),
        ),
    ]
