# Generated by Django 5.1.1 on 2024-12-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_contractpref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractpref',
            old_name='propety_type',
            new_name='property_type',
        ),
    ]
