# Generated by Django 5.1.1 on 2024-12-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_rename_propety_type_contractpref_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pref_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('panel_1', 'Proficent English'), ('panel_2', 'Waiting Interview'), ('panel_3', 'Standby'), ('rejected', 'Rejected'), ('accepted', 'Hired')], default='pending', max_length=50, null=True),
        ),
    ]
