# Generated by Django 5.1.1 on 2024-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_serversetting_clients_webhook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='whatsapp_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
