# Generated by Django 5.1.1 on 2025-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_serversetting_whatsapp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='discovery_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_discovery',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('referral', 'Referral'), ('company_website', 'Company Website'), ('job_portal', 'Job Portal'), ('direct_messages', 'Direct Messages'), ('recruiter', 'Recruiter'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
