# Generated by Django 5.1.1 on 2025-02-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_application_discovery_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_campaign_users', to='core.campaign'),
        ),
    ]
